export const Team = [
    {
        TeamName: "Core Team",
        TeamMembers: [
            {
                Name: "Prit Varmora",
                Designation: "Management, Technical Lead",
                Email: "pritjvarmora14044@gmail.com",
                LinkedIn: "https://www.linkedin.com/in/prit-varmora",
                Github: "https://www.github.com/PRITVARMORA",
                Photo: process.env.PUBLIC_URL + "/Assets/temp-img.jpg",
            },
            {
                Name: "Ritvik Tiwari",
                Designation: "Management, Technical Lead",
                Email: "ritviktiwari50@gmail.com",
                LinkedIn: "https://www.linkedin.com/in/ritvik-tiwari",
                Github: "https://www.github.com/ritvik-tiwari",
                Photo: process.env.PUBLIC_URL + "/Assets/temp-img.jpg",
            },
            {
                Name: "Minu Chaudhary",
                Designation: "Non-Technical Lead",
                Email: "minuchaudhary06@gmail.com",
                LinkedIn: "https://www.linkedin.com/in/minu-chaudhary",
                Github: "https://www.github.com/Minu-Chaudhary",
                Photo: process.env.PUBLIC_URL + "/Assets/temp-img.jpg",
            },
            {
                Name: "Soham Vekariya",
                Designation: "Non-Technical Lead",
                Email: "sohamvekariya111@gmail.com",
                LinkedIn: "https://www.linkedin.com/in/soham-vekariya-6474491b5",
                Github: "https://www.github.com/SohamVekariya",
                Photo: process.env.PUBLIC_URL + "/Assets/temp-img.jpg",
            },
        ]
    },
    {
        TeamName: "Technical Team",
        TeamMembers: [
            {
                Name: "Deep Kanani",
                Email: "deepkanani127@gmail.com",
                LinkedIn: "https://www.linkedin.com/in/deep-kanani-87a513180",
                Github: "https://www.github.com/Deepie127",
                Stars: 0,
                Photo: process.env.PUBLIC_URL + "/Assets/temp-img.jpg",
            },
            {
                Name: "Dhruv Kanyal",
                Email: "dhruvkanyal111@gmail.com",
                LinkedIn: "https://www.linkedin.com/in/dhruv-kanyal-956512180",
                Github: "https://www.github.com/Dhruv118",
                Stars: 0,
                Photo: process.env.PUBLIC_URL + "/Assets/temp-img.jpg",
            },
            {
                Name: "Hardee Bhatt",
                Email: "hardeebhatt263@gmail.com",
                LinkedIn: "https://www.linkedin.com/in/hardee-bhatt-6162681b4",
                Github: "https://www.github.com/Hardee426",
                Stars: 0,
                Photo: process.env.PUBLIC_URL + "/Assets/temp-img.jpg",
            },
            {
                Name: "Het Shah",
                Email: "shahet512@gmail.com",
                LinkedIn: "https://www.linkedin.com/in/het-shah-07b5a41b3",
                Github: "https://www.github.com/HetShah512",
                Stars: 1,
                Photo: process.env.PUBLIC_URL + "/Assets/temp-img.jpg",
            },
            {
                Name: "Kashyap Joshi",
                Email: "joshikashyap379@gmail.com",
                LinkedIn: "https://www.linkedin.com/in/kashyap-joshi-415381191",
                Github: "https://www.github.com/379-kash",
                Stars: 1,
                Photo: process.env.PUBLIC_URL + "/Assets/temp-img.jpg",
            },
            {
                Name: "Kaushal Parmar",
                Email: "kaushalparmar1327@gmail.com",
                LinkedIn: "https://www.linkedin.com/in/kaushal-parmar-0b3517176",
                Github: "https://www.github.com/Kaushal-IN",
                Stars: 0,
                Photo: process.env.PUBLIC_URL + "/Assets/temp-img.jpg",
            },
            {
                Name: "Muskan Vora",
                Email: "muskaanvora0107@gmail.com",
                LinkedIn: "https://www.linkedin.com/in/muskan-vora-7920661a7",
                Github: "https://www.github.com/Muskaan-Vora",
                Stars: 0,
                Photo: process.env.PUBLIC_URL + "/Assets/temp-img.jpg",
            },
            {
                Name: "Namra Shastri",
                Email: "namrashastri001@gmail.com",
                LinkedIn: "https://www.linkedin.com/in/namra-shastri-14321b183",
                Github: "https://www.github.com/Namra561",
                Stars: 1,
                Photo: process.env.PUBLIC_URL + "/Assets/temp-img.jpg",
            },
            {
                Name: "Rishav Singh",
                Email: "rsh04613@gmail.com",
                LinkedIn: "https://www.linkedin.com/in/rishav-singh011",
                Github: "https://www.github.com/rishav-singh-0",
                Stars: 0,
                Photo: process.env.PUBLIC_URL + "/Assets/temp-img.jpg",
            },
            {
                Name: "Sandeep Suthar",
                Email: "sandeepsuthar5301@gmail.com",
                LinkedIn: "https://www.linkedin.com/in/suthar-sandeep-b36a48147/",
                Github: "https://www.github.com/SANDEEP5301",
                Stars: 0,
                Photo: process.env.PUBLIC_URL + "/Assets/temp-img.jpg",
            },
            {
                Name: "Shiv Bhatt",
                Email: "shivbhatt.8@gmail.com",
                LinkedIn: "https://www.linkedin.com/in/shivbhatt08",
                Github: "https://www.github.com/shivbhatt8",
                Stars: 0,
                Photo: process.env.PUBLIC_URL + "/Assets/temp-img.jpg",
            },
            {
                Name: "Shrey Awasthi",
                Email: "shreyawasthi2001@gmail.com",
                LinkedIn: "https://www.linkedin.com/in/shrey-awasthi-1345a41b4",
                Github: "https://www.github.com/shrey1228",
                Stars: 0,
                Photo: process.env.PUBLIC_URL + "/Assets/temp-img.jpg",
            },
        ],
    },
    {
        TeamName: "Ex Team Members",
        TeamMembers: [
            {
                Name: "Kathan Shah",
                Email: "kath9266@gmail.com",
                LinkedIn: "https://www.linkedin.com/in/kathan-shah-b4857a17b",
                Github: "https://www.github.com/kathan-shah99",
                Stars: 1,
                Photo: process.env.PUBLIC_URL + "/Assets/temp-img.jpg",
            },
            {
                Name: "Kartavya Barodiya",
                Email: "kartavya1109@gmail.com",
                LinkedIn: "https://www.linkedin.com/in/kartavya-barodiya-8aa55b183/",
                Github: "https://www.github.com/YantraBoy",
                Stars: 0,
                Photo: process.env.PUBLIC_URL + "/Assets/temp-img.jpg",
            },
            {
                Name: "Krutarth Trivedi",
                Email: "krutarth3ved@gmail.com",
                LinkedIn: "https://www.linkedin.com/in/krutarth-trivedi-029211183",
                Github: "https://www.github.com/krutarth3ved",
                Stars: 1,
                Photo: process.env.PUBLIC_URL + "/Assets/temp-img.jpg",
            },
        ],
    }
]