on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build and Preview
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build project
        uses: actions/setup-node@v2
        with:
          node-version: '12'
        run: |
          npm install
          npm run build
      
      - name: Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 30d
